development:
  adapter: postgresql
  encoding: unicode
  database: house_development
  host: localhost
  pool: 5
  username: bnelson
  password: EDSW94edsw

test:
  adapter: postgresql
  encoding: unicode
  database: house_test
  host: localhost
  pool: 5
  username: bnelson
  password: EDSW94edsw
